"""empty message

Revision ID: 195a8fc23126
Revises: bc91c29cd09f
Create Date: 2020-06-23 01:37:41.919201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '195a8fc23126'
down_revision = 'bc91c29cd09f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', sa.String(), primary_key=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###
