"""empty message

Revision ID: 24801786820a
Revises: 59e99a3a18b8
Create Date: 2020-06-24 18:39:56.706221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24801786820a'
down_revision = '59e99a3a18b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'genres')
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('Artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
