"""empty message

Revision ID: 31521954185e
Revises: 195a8fc23126
Create Date: 2020-06-23 01:54:21.205857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31521954185e'
down_revision = '195a8fc23126'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Show', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Show', 'start_time',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Show', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
